config/routes.rb
Estacionamento::Application.routes.draw do

  devise_for :usuarios

  resources :veiculos
  resources :movimentos do
    put :sair, on: :member
end
  root to: 'home#index'

end

app/models/movimento.rb
class Movimento < ActiveRecord::Base
  belongs_to :veiculo
  validates :veiculo, :placa, presence: true
  validates :placa, format: { with: /^[A-Z]{3}\-[0-9]{4}$/ }

  before_create :definir_hora_entrada

  def definir_hora_entrada
    self.hora_entrada = Time.now
  end

  def sair
    self.hora_saida = Time.now
    save!
  end

  def self.abertos
  	where('hora_saida is NULL')
  end

	def fechado?
		hora_saida.present?
	end

	def valor
		2 * ((hora_saida - hora_entrada) / 3600).ceil
	end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	validates :email, :password, presence: true
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, ,  and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :trackable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/models/veiculo.rb
class Veiculo < ActiveRecord::Base
	validates :tipo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_usuario!

  def index
  end
end

app/controllers/movimentos_controller.rb
class MovimentosController < ApplicationController
	before_filter :authenticate_usuario!

  # GET /movimentos
  # GET /movimentos.json
  def index
    @movimentos = Movimento.abertos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movimentos }
    end
  end

  # GET /movimentos/1
  # GET /movimentos/1.json
  def show
    @movimento = Movimento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movimento }
    end
  end

  # GET /movimentos/new
  # GET /movimentos/new.json
  def new
    @movimento = Movimento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movimento }
    end
  end

  # GET /movimentos/1/edit
  def edit
    @movimento = Movimento.find(params[:id])
  end

  # POST /movimentos
  # POST /movimentos.json
  def create
    @movimento = Movimento.new(params[:movimento])

    respond_to do |format|
      if @movimento.save
        format.html { redirect_to @movimento, notice: 'Movimento was successfully created.' }
        format.json { render json: @movimento, status: :created, location: @movimento }
      else
        format.html { render action: "new" }
        format.json { render json: @movimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movimentos/1
  # PUT /movimentos/1.json
  def update
    @movimento = Movimento.find(params[:id])

    respond_to do |format|
      if @movimento.update_attributes(params[:movimento])
        format.html { redirect_to @movimento, notice: 'Movimento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimentos/1
  # DELETE /movimentos/1.json
  def destroy
    @movimento = Movimento.find(params[:id])
    @movimento.destroy

    respond_to do |format|
      format.html { redirect_to movimentos_url }
      format.json { head :no_content }
    end
  end

def sair
  @movimento = Movimento.find(params[:id])
  @movimento.sair
  redirect_to @movimento
end
end

app/controllers/veiculos_controller.rb
class VeiculosController < InheritedResources::Base
	before_filter :authenticate_usuario!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movimentos_helper.rb
module MovimentosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estacionamento</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="tudo">
		<div id="cabecalho">

				<img src= "/assets/cabecalho.jpg">

		</div>
                            <div id="menucontainer">
								<div id="menunav">
									<% if usuario_signed_in? %>
										<ul>
											<li><%= link_to 'Movimento de Veiculo', new_movimento_path %></li>
											<li><%= link_to 'Relatorio',new_movimento_path %></li>
											<li><%= link_to 'Cadastro de Veiculo', new_veiculo_path %></li>
											<li><%= link_to 'Cadastrar Usuário', new_usuario_registration_path %></li>
											<li><%= link_to 'Sair do Sistema', destroy_usuario_session_path, method: :delete %></li>
										</ul>
									<% end %>
								</div>
							</div>
			<div id = "conteudo">

<%= yield %>

			</div>
		<div id="rodape">
				<img src= "/assets/rodape.jpg">
		</div>
</div>

</body>
</html>

app/views/movimentos/_form.html.erb
<%= semantic_form_for(@movimento) do |f| %>
  <%= f.input :veiculo, :member_label => :tipo %>
  <%= f.input :placa %>
  <%= f.submit %>
<% end %>

app/views/movimentos/edit.html.erb
<div id ="conteudo">
	<h1>Alterar Movimentos</h1>
		<div id ="lista">
			<%= render 'form' %>

			<%= link_to 'Visualizar', @movimento %> |
			<%= link_to 'Voltar', movimentos_path %>
		</div>
</div>

app/views/movimentos/index.html.erb
<div id = "conteudo">
	<h1>Lista de Movimentos</h1>
	<div id= "lista">
		<table>
  <tr>
    <th>Veiculo</th>
    <th>Placa</th>
    <th>Entrada</th>
    <th>Saida</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movimentos.each do |movimento| %>
  <tr>
    <td><%= movimento.veiculo.tipo %></td>
    <td><%= movimento.placa %></td>
    <td><%= movimento.hora_entrada.strftime("%d/%m/%Y %H:%M") %></td>
    <td><%= movimento.hora_saida.strftime("%d/%m/%Y %H:%M") if movimento.hora_saida %></td>
    <td><%= link_to 'Saída', sair_movimento_path(movimento), method: :put %></td>
    <td><%= link_to 'Editar', edit_movimento_path(movimento) %></td>
    <td><%= link_to 'Deletar', movimento, confirm: 'Voce quer deletar?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br/>

<%= link_to 'Novo Movimento', new_movimento_path %>
</div>
</div>

app/views/movimentos/new.html.erb
<div id="conteudo">
  <h1>Entrada Veiculo</h1>
<br><br>
	<div id="lista">
	<table>
	<tr>
		<td>
			<%= render 'form' %>
		</td>
	</tr>
	</table>

		<%= link_to 'Saida do Veiculo', movimentos_path %>
	</div>
</div>

app/views/movimentos/show.html.erb
<p id="notice"><%= notice %></p>
<div id="conteudo">
<table class="movimentoshow">
<tr>
	<td>
		<b>Veiculo:</b>
 		<%= @movimento.veiculo.tipo %>
	</td>
</tr>

<tr>
	<td>
		  <b>Placa:</b>
		  <%= @movimento.placa %>
</tr>

<tr>
	<td>
  <b>Hora entrada:</b>
  <%= @movimento.hora_entrada %>
</td>
</tr>

<% if @movimento.fechado? %>
<tr>
	<td>
		<b>Hora saida:</b>
		<%= @movimento.hora_saida %>
	</td>
</tr>
<tr>
	<td>
		<b>Valor:</b>
		<%= @movimento.valor %>
</tr>
<% end %>
	</tr>
</table>
<p>
<%= link_to 'Editar', edit_movimento_path(@movimento) %> |
<%= link_to 'Voltar', movimentos_path %>
</p>
</div>

app/views/veiculos/_form.html.erb
<%= semantic_form_for(@veiculo) do |f| %>
	<%= f.input :tipo %>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<div id= "conteudo">
	<h1>Alterar Veiculo</h1>
		<div id ="lista">
			<%= render 'form' %>

			<%= link_to 'Visualizar', @veiculo %> |
			<%= link_to 'Voltar', veiculos_path %>
		</div>

</div>

app/views/veiculos/index.html.erb
<div id ="conteudo">
  <h1>Lista de Veiculos</h1>
    <div id="lista">
      <table>
          <tr>
            <th>Tipo</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

            <% @veiculos.each do |veiculo| %>
              <tr>
                <td><%= veiculo.tipo %></td>
                <td><%= link_to 'Visualizar', veiculo %></td>
                <td><%= link_to 'Alterar', edit_veiculo_path(veiculo) %></td>
                <td><%= link_to 'Deletar', veiculo, confirm: 'Deletar?', method: :delete %></td>
              </tr>
            <% end %>
      </table>
        <br/>
      <%= link_to 'Cadastrar Novo Veiculo', new_veiculo_path %>
    </div>
</div    

app/views/veiculos/new.html.erb
<div id="conteudo">
	<h1>Entrada de Veiculo</h1>
		<div id="lista">
			<%= render 'form' %>

			<%= link_to 'Voltar', veiculos_path %>
		</div>
</div>

app/views/veiculos/show.html.erb
<div id="conteudo">
	<div id="lista">
		<p id="notice"><%= notice %></p>
  		<table>
          <tr>
            <td><b>Tipo:</b></td>
          	<td><%= @veiculo.tipo %></td>
          </tr>

   			</table>
   			<br>
					<%= link_to 'Alterar', edit_veiculo_path(@veiculo) %> |
					<%= link_to 'Voltar', veiculos_path %>
		</div>
</div>